version: '2'
services:
    kuskiapppp-app:
        image: kuskiapppp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kuskiapppp-mysql:3306/kuskiapppp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=kuskiapppp-elasticsearch:9300
        ports:
            - 8080:8080
    kuskiapppp-mysql:
        extends:
            file: mysql.yml
            service: kuskiapppp-mysql
    kuskiapppp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: kuskiapppp-elasticsearch
